export const ROUTES = {
  login: "/",
  register: "/register",
  start: (id?: number) => (id !== undefined ? `/start/${id}` : "/start"),
  game: (id: number) => `/game/${id}`,
  gamePattern: "/game/:id",
  summary: (id: number) => `/summary/${id}`,
  summaryPattern: "/summary/:id",
  details: (id: number) => `/details/${id}`,
  detailsPattern: "/details/:id",
  gamesOverview: "/gamesoverview",
  settings: (id?: number) => (id !== undefined ? `/settings/${id}` : "/settings"),
  statistics: "/statistics",
  joined: "/joined",
  playerProfile: "/playerprofile",
} as const;
